version: "3.8"

services:
  db:
    restart: always
    image: mysql:8.0
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 4306:3306
  redis:
    image: redis:6.2.1
    ports:
        - 6379:6379
  nchan:
    image: weseek/nginx-nchan
    container_name: nchan
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - redis
  ingame:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: "air"
    env_file: ./.envrc.docker.local
    volumes:
      - .:/himo-ingame
      - bin:/himo-ingame/bin
    ports:
      - "8080:8080"
volumes:
  bin:
