version: "3.8"

services:
  redis:
    restart: always
    image: redis:6.0.9
    ports:
        - 6379:6379
    networks:
      - himo_links
  nchan:
    restart: always
    image: weseek/nginx-nchan
    container_name: nchan
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - redis
    networks:
      - himo_links
  ingame:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: "air"
    env_file: ./.envrc.docker.local
    volumes:
      - .:/himo-ingame
      - bin:/himo-ingame/bin
    ports:
      - "8080:8080"
    networks:
      - himo_links
volumes:
  bin:

# devサーバーで ingame が先に立っていた outgame の db service をみるためにネットワークを指定
# 上記の理由から db はこの yaml から消している
networks:
  himo_links:
    external: true
