version: "3.8"

services:
  redis:
    restart: always
    image: redis:6.0.9
    ports:
        - 6379:6379
    networks:
      - himo_links
  nginx-nchan:
    restart: always
    image: weseek/nginx-nchan
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - redis
    networks:
      - himo_links
  ingame:
    restart: always
    image: bamboooo/himo-ingame
    env_file: ./.envrc.docker.local
    command: "./bin/ingame"
    ports:
      - 8080:8080
    networks:
      - himo_links

# devサーバーで ingame が先に立っていた outgame の db service をみるためにネットワークを指定
# 上記の理由から db はこの yaml から消している
networks:
  himo_links:
    external: true
