version: "3.8"

services:
  redis:
    restart: always
    image: redis:6.2.1
    ports:
        - 6379:6379
    networks:
      - himo_links
  nchan:
    restart: always
    image: weseek/nginx-nchan
    container_name: nchan
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - redis
    networks:
      - himo_links
  ingame:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.envrc.docker.local
    command: "./bin/ingame"
    ports:
      - 8080:8080
    networks:
      - himo_links

# devサーバーで ingame が先に立っていた outgame の db service をみるためにネットワークを指定
# 上記の理由から db はこの yaml から消している
networks:
  himo_links:
    external: true
