FROM golang:1.17.0-alpine3.13

RUN apk --update --no-cache add git build-base openssh curl nmap mysql-client bash jq

COPY install.sh ./
RUN cat install.sh | sh -s -- -b $(go env GOPATH)/bin

WORKDIR /himo-ingame

COPY go.mod go.sum /himo-ingame/
RUN go mod download

COPY . /himo-ingame

RUN chmod 755 ./entry-point.sh
ENTRYPOINT [ "./entry-point.sh" ]
