version: "3.8"

services:
  db:
    restart: always
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  redis:
    restart: always
    image: redis:6.0.9
    ports:
        - 6379:6379
  nginx-nchan:
    restart: always
    image: weseek/nginx-nchan
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - redis
  ingame:
    restart: always
    image: bamboooo/himo-ingame
    command: "./bin/ingame"
    ports:
      - 8080:8080
    depends_on:
      - mysql
